[[redirects]]
  from = "/api/*"
  to = "https://redditbackend4.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { 
    X-Forwarded-Host = "auuu.netlify.app",
    Access-Control-Allow-Origin = "*"
  }