[[redirects]]
  from = "/api/*"
  to = "https://redditbackend4.onrender.com/api/:splat"  # /api/fetch/avengedsevenfold → /api/fetch/avengedsevenfold
  status = 200
  force = true
  headers = {X-Forwarded-Host = "auuu.netlify.app"}

# Eğer /api/reddit/* altında özel bir yönlendirme gerekiyorsa:
[[redirects]]
  from = "/api/reddit/*"
  to = "https://redditbackend4.onrender.com/api/reddit/:splat"  # /api/reddit/fetch → /api/reddit/fetch
  status = 200
  force = true
  headers = {X-Forwarded-Host = "auuu.netlify.app"}

  [[redirects]]
  from = "/api/fetch/:subreddit"  # Dinamik segment yakalama
  to = "https://redditbackend4.onrender.com/api/fetch/:subreddit"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "auuu.netlify.app"}

[[redirects]]
  from = "/api/posts/:subreddit"  # Diğer dinamik route
  to = "https://redditbackend4.onrender.com/api/posts/:subreddit"
  status = 200
  force = true
  headers = {X-Forwarded-Host = "auuu.netlify.app"}